---
- name: Setup Openstack MQ user
  rabbitmq_user:
    user: '{{ openstack_message_broker_user_name }}'
    password: '{{ openstack_message_broker_user_pass }}'
  sudo: true
  sudo_user: rabbitmq
  delegate_to: '{{ openstack_message_queue_node_name }}'

- name: Create Admin environment file
  template:
    src: admin-openrc.sh.j2
    dest: /root/admin-openrc.sh
    owner: root
    group: root
    mode: 384
  tags: admin_env_file